### ISSUE TITLE
update notebook to use new cloud object storage

### ISSUE THREAD

**Issue by stevemar** [IBM/iot-predictive-analytics#4]
this code pattern should be updated to use the new cloud object service (not the swift based one).

The file https://github.com/IBM/iot-predictive-analytics/blob/master/notebook/watson_iotfailure_prediction.ipynb should be updated like this one was: IBM/pixiedust-facebook-analysis@b22714a -- as well as the instructions in the README.

If i recall correctly, @balajikadambi has updated a few notebooks already, suggest pinging him to get a better understanding.

**Comment by dkprabu** [comment]
@stevemart I have made necessary changes to take care of new Cloud storage service as well as Python 3.5 upgraded environment. My updated file here: (https://github.com/dkprabu/iotpredictive/blob/master/changecloudstorage/watson_iotfailure_prediction.ipynb). Please let me know if I can go ahead and push this file in the repo myself or please help me do so.

**Comment by stevemar** [comment]
@dkprabu you should have write access to this repo too. you can commit your changes to this repo the same way you did it for https://github.com/IBM/detect-timeseriesdata-change :)

**Comment by dkprabu** [comment]
@stevemart Comitted the changes. thank you
